plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'fr.pandonia'
version = '1.0-SNAPSHOT'
description = 'The implementation of the server in which players connect after joining the network'

repositories {
    mavenCentral()

    maven {
        name 'spigotmc-repo'
        url 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/'
    }

    maven {
        name 'jitpack'
        url 'https://jitpack.io'
    }
}

dependencies {
    compileOnly 'org.bukkit:bukkit:1.8.8-R0.1-SNAPSHOT'

    // Gui
    implementation 'com.samjakob:SpiGUI:v1.3.1'

    // Sql
    implementation 'com.zaxxer:HikariCP:4.0.3'
    implementation 'com.mysql:mysql-connector-j:8.3.0'

    // Logging
    runtimeOnly 'org.slf4j:slf4j-simple:2.0.13'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

processResources {
    filter {
        it.replace('${description}', project.description)
        it.replace('${version}', project.version)
    }
}

shadowJar {
    archiveFileName = "${project.name}-${project.version}.jar"
}
