hub: 1

database:
  host: localhost
  port: 3306
  username: root
  password: root
  database: pandonia

locations:
  spawn:
    ==: org.bukkit.Location
    world: world
    x: 0
    y: 64
    z: 0
    yaw: 0
    pitch: 0
  jump:
    ==: org.bukkit.Location
    world: world
    x: 0
    y: 64
    z: 0
    yaw: 0
    pitch: 0